// Single entry point for the inline visualization widgets: the SVG core +
// dispatcher and every chart/plot/table widget. Brand-agnostic (see jb.vizTheme
// in viz-core.js); the LLM doclets are applet-specific and imported by each agent.
import './viz-core.js'

import './widgets/pie-widget.js'
import './widgets/bar-widget.js'
import './widgets/hbar-widget.js'
import './widgets/grouped-bar-widget.js'
import './widgets/stacked-bar-widget.js'
import './widgets/line-widget.js'
import './widgets/area-widget.js'
import './widgets/scatter-widget.js'
import './widgets/bubble-widget.js'
import './widgets/histogram-widget.js'
import './widgets/boxplot-widget.js'
import './widgets/heatmap-widget.js'
import './widgets/radar-widget.js'
import './widgets/funnel-widget.js'
import './widgets/gauge-widget.js'
import './widgets/treemap-widget.js'
import './widgets/waterfall-widget.js'
import './widgets/table-widget.js'
import './widgets/kpi-widget.js'
import './widgets/bullet-widget.js'
