export { EditorState, StateEffect, StateField } from '@codemirror/state'
export { EditorView, Decoration, WidgetType, keymap } from '@codemirror/view'
export { syntaxHighlighting, foldGutter, foldAll, unfoldAll } from '@codemirror/language'
export { defaultHighlightStyle } from '@codemirror/language'
export { javascript } from '@codemirror/lang-javascript'
export { html } from '@codemirror/lang-html'
export { lineNumbers, highlightActiveLineGutter } from '@codemirror/view'
export { search, openSearchPanel } from '@codemirror/search'
export { oneDark } from '@codemirror/theme-one-dark'
