FROM node:24.3
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y g++ make python3 unzip --no-install-recommends \
 && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci
